#!/usr/bin/env bash
set -euo pipefail

NPM_INSTALL_CMD="${NPM_INSTALL_CMD:-npm install --save-dev --save-exact}"

# https://stackoverflow.com/a/246128/465684
SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  # if $SOURCE was a relative symlink,
  # we need to resolve it relative to the path where the symlink file was located
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

function exe() {
    echo "$(pwd)\$ $@"
    "$@"
}

node -e " \
    peerDeps = require('${DIR}/package.json').peerDependencies; \
    Object.keys(peerDeps).forEach(function(name) { \
        console.log(name + '\t' + peerDeps[name]); \
    }); \
    " | {
    NPM_PEER_DEPS=""
    while read LINE; do
        NAME=$(echo "${LINE}" | cut -d$'\t' -f1)
        VSN=$(echo "${LINE}" | cut -d$'\t' -f2)

        # is the version already specified in dependencies or devDependencies?
        node -p "try {var pkg = require('./package.json'); var vsn = pkg.dependencies[\"${NAME}\"] || pkg.devDependencies[\"${NAME}\"]; vsn === \"${VSN}\"} catch(err){false}" | \
            grep -q "^false$" || {
          echo ${NAME} ${VSN}
          # if yes, is it already installed?

          node -p "try {var pkg = require('./node_modules/${NAME}/package.json'); pkg.version === \"${VSN}\"} catch(err){false}" | \
              grep -q "^false$" || \
              continue

          node -p "try {var pkg = require('./node_modules/${NAME}/package.json'); pkg._requested && pkg._requested.rawSpec === \"${VSN}\"} catch(err){false}" | \
              grep -q "^false$" || \
              continue
        }

        # NOTE: assumes all peerDeps have semver vers, not git urls, etc
        NPM_PEER_DEPS="${NPM_PEER_DEPS} ${NAME}@${VSN}"
    done
    [ -z "${NPM_PEER_DEPS}" ] || ${NPM_INSTALL_CMD} ${NPM_PEER_DEPS}
}
