#!/usr/bin/env bash
set -euo pipefail

# https://stackoverflow.com/a/246128/465684
SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  # if $SOURCE was a relative symlink,
  # we need to resolve it relative to the path where the symlink file was located
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

function exe() {
    echo "$(pwd)\$ $@"
    "$@"
}

node -e " \
    peerDeps = require('${DIR}/package.json').peerDependencies; \
    Object.keys(peerDeps).forEach(function(name) { \
        console.log(name + '\t' + peerDeps[name]); \
    }); \
    " | {
    NPM_INSTALL_ARGS=""
    while read LINE; do
        NAME=$(echo "${LINE}" | cut -d$'\t' -f1)
        VER=$(echo "${LINE}" | cut -d$'\t' -f2)

        # NOTE: assumes all peerDeps have semver vers, not git urls, etc
        NPM_INSTALL_ARGS="${NPM_INSTALL_ARGS} ${NAME}@${VER}"
    done
    npm install --save-dev --save-exact ${NPM_INSTALL_ARGS}
}
